name: build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_cpp_test
          dev-files: true
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd %TEMP%
          git clone --branch v0.8.2 https://github.com/pgvector/pgvector.git
          cd pgvector
          nmake /NOLOGO /F Makefile.win
          nmake /NOLOGO /F Makefile.win install

      - run: cmake -S . -B build -DBUILD_TESTING=ON -DCMAKE_CXX_STANDARD=20
      - run: cmake --build build
      - run: build/test

      - run: cmake -S . -B build -DBUILD_TESTING=ON -DCMAKE_CXX_STANDARD=23
      - run: cmake --build build
      - run: build/test

      - if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get install valgrind
          valgrind --leak-check=yes --error-exitcode=1 build/test

      # test install
      - run: rm -r build
      - run: cmake -S . -B build
      - run: cmake --build build
      - run: sudo cmake --install build
