name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_cpp_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.8.1 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install

      - run: cmake -S . -B build -DBUILD_TESTING=ON -DCMAKE_CXX_STANDARD=17
      - run: cmake --build build
      - run: build/test

      - run: cmake -S . -B build -DBUILD_TESTING=ON -DCMAKE_CXX_STANDARD=20
      - run: cmake --build build
      - run: build/test

      - run: |
          sudo apt-get install valgrind
          valgrind --leak-check=yes build/test

      # test install
      - run: rm -r build
      - run: cmake -S . -B build
      - run: cmake --build build
      - run: sudo cmake --install build
